=begin comment

Classify

Classify Custom Image Recognition Service

The version of the OpenAPI document: 1.0.0
Contact: info@inoven.ai
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::DefaultApi');

my $api = WWW::OpenAPIClient::DefaultApi->new();
isa_ok($api, 'WWW::OpenAPIClient::DefaultApi');

#
# create_new_model test
#
{
    my $model_name = undef; # replace NULL with a proper value
    my $result = $api->create_new_model(model_name => $model_name);
}

#
# delete_model test
#
{
    my $model_id = undef; # replace NULL with a proper value
    my $result = $api->delete_model(model_id => $model_id);
}

#
# get_models_list test
#
{
    my $result = $api->get_models_list();
}

#
# tag_image_by_url test
#
{
    my $model_id = undef; # replace NULL with a proper value
    my $image_url = undef; # replace NULL with a proper value
    my $result = $api->tag_image_by_url(model_id => $model_id, image_url => $image_url);
}

#
# tag_local_image test
#
{
    my $model_id = undef; # replace NULL with a proper value
    my $file = undef; # replace NULL with a proper value
    my $result = $api->tag_local_image(model_id => $model_id, file => $file);
}

#
# update_model test
#
{
    my $model_name = undef; # replace NULL with a proper value
    my $model_id = undef; # replace NULL with a proper value
    my $result = $api->update_model(model_name => $model_name, model_id => $model_id);
}


1;
